---
###############################################################################
#
# package_absent.yml
#
###############################################################################

###############################################################################
# SETTING VARIABLES
###############################################################################

- name: "Checking if required variables are defined"
  ansible.builtin.assert:
    that:
      - iac_package is defined
    fail_msg: "All tests did not pass"

###############################################################################
# ENSURING PACKAGE IS ABSENT
###############################################################################

- name: "Ensuring packages are absent"
  ansible.builtin.dnf:
  args:
    name: "{{ iac_package }}"
    sslverify: "{{ iac_dnf_sslverify | default(dnf_sslverify | default(true)) }}"
    validate_certs: "{{ iac_dnf_validate_certs | default(dnf_validate_certs | default(true)) }}"
    disable_gpg_check: "{{ iac_dnf_disable_gpg_check | default(dnf_disable_gpg_check | default(false)) }}"
    state: "absent"
  environment:
    http_proxy: "{{ http_proxy | default(omit) }}"
    https_proxy: "{{ https_proxy | default(omit) }}"
    no_proxy: "{{ no_proxy | default(omit) }}"
  register: iac_package_operation
  when: iac_package is defined

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Ensured {{ iac_package }} was uninstalled"
  when: iac_package is defined
