---
- name: "Enable the autoconfigured site through the unified path"
  ansible.builtin.file:
    src: "{{ nginx_etc_directory }}/sites-available/{{ nginx_site.name }}"
    dest: "{{ nginx_etc_directory }}/sites-enabled/{{ nginx_site.name }}"
    owner: root
    group: root
    state: "link"
  notify: "Validate Nginx configuration"
