---
###############################################################################
#
# started.yml
#
# @author Arsi Atomi
#
###############################################################################

###############################################################################
# ENSURING SYSTEMD SERVICE IS STARTED
###############################################################################

- name: "Test Nginx configuration before service start"
  ansible.builtin.command: "/usr/sbin/nginx -t"
  changed_when: false

- name: "Ensure Nginx is started without changing boot enablement"
  ansible.builtin.systemd:
    name: "{{ iac_service_name }}"
    state: "started"
    daemon_reload: true

- name: "Writing log"
  ansible.builtin.include_tasks: log_write.yml
  vars:
    iac_log_write: "Started/restarted service nginx"
