---
- name: "Check Nginx service state before reload"
  ansible.builtin.service_facts:
  listen: "Validate Nginx configuration"

- name: "Validate Nginx configuration"
  ansible.builtin.command: "nginx -t"
  changed_when: false
  listen: "Validate Nginx configuration"
  notify: "Reload Nginx"

- name: "Reload Nginx"
  ansible.builtin.service:
    name: "nginx"
    state: "reloaded"
  when: >-
    ((ansible_facts.services['nginx.service'] |
    default(ansible_facts.services['nginx'] | default({}))).state |
    default('stopped')) == 'running'
  listen: "Reload Nginx"
